### PR TITLE
Update role for HTCondor 10.x

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**
Hello,

I would like to use this Ansible role in IM, and I am updating it to support:
* HTCondor 10.x
* OSes: RHEL 7, 8, 9 and Ubuntu 20.04, 22.04

Please review and let me know your thoughts.

Best regards,
Sebastian

### CODE REVIEW

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

Could you merge master updates in your fork?

**Comment by sebastian-luna-valero** [comment]
Sure, it's done @micafer

**Comment by micafer** [comment]
Hi @sebastian-luna-valero,

I have created a new branch htcondor-10.x in this repo.
I made some modifications, I will close this PR, and create a new one from the branch.
We can work together in this new branch.

Thanks for this contribution.

**Comment by sebastian-luna-valero** [comment]
Thanks @micafer 

xref: https://github.com/grycap/ansible-role-htcondor/pull/12

**Pull request closed without merging**
